### ISSUE TITLE
Relax Julia version 1.3 compat requirements

### ISSUE THREAD

**Issue by mossr** [rbalexan/BenchmarkFunctions.jl#16]
Hey Ross! I installed your package with Julia v1.2 and all tests pass without issue. Every time I interact with `Pkg` I get warnings that BenchmarkFunctions does not satisfy compat requirements for Julia v1.3, but it seems like you could relax the requirements to at least v1.2. 

Was there a specific reason for marking it at v1.3? Or was that simply the version you were using at the time? By the way, excellent work on this package!

**Comment by rbalexan** [comment]
Hey Robert! I think I was developing with v1.3 and eventually v1.4, but we can probably bump the compat down to v1.2.

Thanks! I started developing the package as a way to get more familiar with Julia packages and the general registry process. Haven't gotten back to it in a while, but I definitely would like to expand and improve everything. Always open to any ideas via issues!

**Comment by mossr** [comment]
If I think of any improvements I'll be sure to submit an issue!

FYI, I just submitted a PR with the v1.2 relaxation.

**Comment by rbalexan** [comment]
Resolved by #17
